version: 1.0.{build}
os: Visual Studio 2019
skip_tags: true
configuration: Release

environment:
  CHOCOLATEYKEY:
    secure: FN8rbgEXxUUmIbLsYpsvaAMmTidJQEyNJMhgU+ggl4H/n2luoWRO+eitNbi6FYPI

before_build:
  - ps: .\Scripts\set-version.ps1
  - cmd: nuget restore
  - choco install checksum
  - choco install 7zip

build_script:
  - cmd: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
  #- cmd: dotnet publish -r win-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:PublishTrimmed=true

after_build:
  #- ps: .\Scripts\GoRepack.ps1
  - ps: .\CreateChocoPackage\CreatePackage.ps1
  - ps: .\CreateChocoPackage\PushPackage.ps1

artifacts:
  - path: DeveImageOptimizerWPF\bin\Release\netcoreapp3.1\win-x64\publish\*.exe
    name: droppackage
  - path: CreateChocoPackage\*.nupkg
    name: chocopackage

deploy:
  - provider: GitHub
    auth_token:
      secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
    artifact: droppackage
